name: '(Deprecated) Open in CodeSandbox'
description: 'GitHub Action that makes it easy to review your work in CodeSandbox.'
branding:
  icon: 'square'
  color: 'black'
runs:
  using: 'composite'
  steps:
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: |
          console.log("This action is deprecated. Please use our GitHub App instead: https://github.com/apps/codesandbox");
